In [21]:
import pandas as pd
from matplotlib import pyplot
from statsmodels.tsa.arima.model import ARIMA

C:\Users\Caesar\AppData\Local\Temp\ipykernel_27140\797599868.py:3: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  from pandas import datetime

In [23]:
df = pd.read_csv('filtered-data.csv')

In [25]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='%Y-%m-%d')

In [28]:
df.head()

,Unnamed: 0,Suburb,Rooms,Price,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea,Type_h,Type_t,Type_u,Method_PI,Method_S,Method_SA,Method_SP,Method_VB
0,0,0,3,1490000.0,180,2017-04-01,3067,2,4019,3.0,32,1,0,0,0,1,0,0,0
1,1,0,3,1220000.0,225,2017-04-01,3067,2,4019,3.0,32,1,0,0,0,1,0,0,0
2,2,0,3,1420000.0,253,2017-04-01,3067,2,4019,3.0,32,1,0,0,0,1,0,0,0
3,3,1,3,1515000.0,28,2017-04-01,3040,6,1543,7.5,22,1,0,0,0,1,0,0,0
4,4,2,2,670000.0,253,2017-04-01,3042,6,3464,10.4,22,1,0,0,0,1,0,0,0

In [29]:
df.describe()

,Unnamed: 0,Suburb,Rooms,Price,SellerG,Postcode,Regionname,Propertycount,Distance,CouncilArea,Type_h,Type_t,Type_u,Method_PI,Method_S,Method_SA,Method_SP,Method_VB
count,48433.000000,48433.000000,48433.000000,4.843300e+04,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000,48433.000000
mean,31561.112465,180.972808,3.071666,9.978982e+05,206.521442,3123.210332,3.449590,7566.399913,12.702761,14.032106,0.705325,0.102822,0.191853,0.122644,0.632296,0.007536,0.133793,0.103731
std,18215.490268,103.813998,0.944708,5.934989e+05,121.296754,125.534940,2.120654,4457.405884,7.550030,10.129363,0.455901,0.303730,0.393762,0.328031,0.482185,0.086484,0.340433,0.304914
min,0.000000,0.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,39.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15796.000000,88.000000,2.000000,6.200000e+05,105.000000,3051.000000,2.000000,4280.000000,7.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,31586.000000,176.000000,3.000000,8.300000e+05,222.000000,3103.000000,4.000000,6567.000000,11.700000,12.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,47364.000000,275.000000,4.000000,1.220000e+06,308.000000,3163.000000,5.000000,10412.000000,16.700000,22.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
max,63020.000000,369.000000,31.000000,1.120000e+07,421.000000,3980.000000,7.000000,21650.000000,55.800000,33.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48433 entries, 0 to 48432
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     48433 non-null  int64
 1   Suburb         48433 non-null  int64
 2   Rooms          48433 non-null  int64
 3   Price          48433 non-null  float64
 4   SellerG        48433 non-null  int64
 5   Date           48433 non-null  datetime64[ns]
 6   Postcode       48433 non-null  int64
 7   Regionname     48433 non-null  int64
 8   Propertycount  48433 non-null  int64
 9   Distance       48433 non-null  float64
 10  CouncilArea    48433 non-null  int64
 11  Type_h         48433 non-null  int64
 12  Type_t         48433 non-null  int64
 13  Type_u         48433 non-null  int64
 14  Method_PI      48433 non-null  int64
 15  Method_S       48433 non-null  int64
 16  Method_SA      48433 non-null  int64
 17  Method_SP      48433 non-null  int64
 18  Method_VB      48433 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(16)
memory usage: 7.0 MB

In [31]:
df["Date"].unique()

array(['2017-04-01T00:00:00.000000000', '2017-07-01T00:00:00.000000000',
       '2018-09-01T00:00:00.000000000', '2018-06-02T00:00:00.000000000',
       '2018-02-03T00:00:00.000000000', '2018-03-03T00:00:00.000000000',
       '2017-06-03T00:00:00.000000000', '2016-09-03T00:00:00.000000000',
       '2017-09-03T00:00:00.000000000', '2016-12-03T00:00:00.000000000',
       '2016-02-04T00:00:00.000000000', '2017-03-04T00:00:00.000000000',
       '2016-06-04T00:00:00.000000000', '2018-08-04T00:00:00.000000000',
       '2017-11-04T00:00:00.000000000', '2018-05-05T00:00:00.000000000',
       '2018-01-06T00:00:00.000000000', '2017-05-06T00:00:00.000000000',
       '2016-08-06T00:00:00.000000000', '2018-10-06T00:00:00.000000000',
       '2018-04-07T00:00:00.000000000', '2016-05-07T00:00:00.000000000',
       '2018-07-07T00:00:00.000000000', '2017-10-07T00:00:00.000000000',
       '2016-11-07T00:00:00.000000000', '2018-01-08T00:00:00.000000000',
       '2017-04-08T00:00:00.000000000', '2017-07-08T00:00:00.000000000',
       '2018-09-08T00:00:00.000000000', '2016-10-08T00:00:00.000000000',
       '2018-06-09T00:00:00.000000000', '2017-09-09T00:00:00.000000000',
       '2017-12-09T00:00:00.000000000', '2018-02-10T00:00:00.000000000',
       '2018-03-10T00:00:00.000000000', '2016-09-10T00:00:00.000000000',
       '2016-12-10T00:00:00.000000000', '2017-02-11T00:00:00.000000000',
       '2017-03-11T00:00:00.000000000', '2018-08-11T00:00:00.000000000',
       '2017-11-11T00:00:00.000000000', '2018-05-12T00:00:00.000000000',
       '2016-06-12T00:00:00.000000000', '2017-08-12T00:00:00.000000000',
       '2016-11-12T00:00:00.000000000', '2017-05-13T00:00:00.000000000',
       '2016-08-13T00:00:00.000000000', '2018-10-13T00:00:00.000000000',
       '2018-04-14T00:00:00.000000000', '2016-05-14T00:00:00.000000000',
       '2018-07-14T00:00:00.000000000', '2017-10-14T00:00:00.000000000',
       '2017-07-15T00:00:00.000000000', '2018-09-15T00:00:00.000000000',
       '2016-10-15T00:00:00.000000000', '2016-04-16T00:00:00.000000000',
       '2018-06-16T00:00:00.000000000', '2016-07-16T00:00:00.000000000',
       '2017-09-16T00:00:00.000000000', '2017-12-16T00:00:00.000000000',
       '2018-02-17T00:00:00.000000000', '2018-03-17T00:00:00.000000000',
       '2017-06-17T00:00:00.000000000', '2016-09-17T00:00:00.000000000',
       '2017-03-18T00:00:00.000000000', '2016-06-18T00:00:00.000000000',
       '2018-08-18T00:00:00.000000000', '2017-11-18T00:00:00.000000000',
       '2018-05-19T00:00:00.000000000', '2017-08-19T00:00:00.000000000',
       '2016-11-19T00:00:00.000000000', '2018-01-20T00:00:00.000000000',
       '2017-05-20T00:00:00.000000000', '2018-04-21T00:00:00.000000000',
       '2018-07-21T00:00:00.000000000', '2017-10-21T00:00:00.000000000',
       '2017-04-22T00:00:00.000000000', '2016-05-22T00:00:00.000000000',
       '2017-07-22T00:00:00.000000000', '2016-08-22T00:00:00.000000000',
       '2018-09-22T00:00:00.000000000', '2016-04-23T00:00:00.000000000',
       '2018-06-23T00:00:00.000000000', '2017-09-23T00:00:00.000000000',
       '2017-12-23T00:00:00.000000000', '2018-02-24T00:00:00.000000000',
       '2018-03-24T00:00:00.000000000', '2017-06-24T00:00:00.000000000',
       '2016-09-24T00:00:00.000000000', '2017-02-25T00:00:00.000000000',
       '2018-08-25T00:00:00.000000000', '2017-11-25T00:00:00.000000000',
       '2018-05-26T00:00:00.000000000', '2016-07-26T00:00:00.000000000',
       '2017-08-26T00:00:00.000000000', '2018-01-27T00:00:00.000000000',
       '2017-05-27T00:00:00.000000000', '2016-06-27T00:00:00.000000000',
       '2016-11-27T00:00:00.000000000', '2016-01-28T00:00:00.000000000',
       '2018-04-28T00:00:00.000000000', '2016-05-28T00:00:00.000000000',
       '2018-07-28T00:00:00.000000000', '2016-08-28T00:00:00.000000000',
       '2017-10-28T00:00:00.000000000', '2017-04-29T00:00:00.000000000',
       '2017-07-29T00:00:00.000000000', '2018-06-30T00:00:00.000000000',
       '2016-07-30T00:00:00.000000000', '2017-09-30T00:00:00.000000000',
       '2017-12-30T00:00:00.000000000', '2018-03-31T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [33]:
! pip install statsForecast

from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
C:\Users\Caesar\anaconda3\lib\site-packages\statsforecast\core.py:21: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

Collecting statsForecast
  Downloading statsforecast-1.5.0-py3-none-any.whl (99 kB)
     ------------------------------------ 100.0/100.0 kB 147.1 kB/s eta 0:00:00
Collecting fugue>=0.8.1
  Downloading fugue-0.8.3-py3-none-any.whl (372 kB)
     ------------------------------------ 372.4/372.4 kB 108.8 kB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.5 in c:\users\caesar\anaconda3\lib\site-packages (from statsForecast) (1.4.4)
Requirement already satisfied: scipy>=1.7.3 in c:\users\caesar\anaconda3\lib\site-packages (from statsForecast) (1.9.1)
Requirement already satisfied: plotly in c:\users\caesar\anaconda3\lib\site-packages (from statsForecast) (5.9.0)
Requirement already satisfied: tqdm in c:\users\caesar\anaconda3\lib\site-packages (from statsForecast) (4.64.1)
Requirement already satisfied: numba>=0.55.0 in c:\users\caesar\anaconda3\lib\site-packages (from statsForecast) (0.55.1)
Collecting plotly-resampler
  Downloading plotly_resampler-0.8.3.2.tar.gz (46 kB)
     --------------------------------------- 46.4/46.4 kB 59.3 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: matplotlib in c:\users\caesar\anaconda3\lib\site-packages (from statsForecast) (3.5.2)
Collecting numpy>=1.21.6
  Downloading numpy-1.24.2-cp39-cp39-win_amd64.whl (14.9 MB)
     ---------------------------------------- 14.9/14.9 MB 1.5 MB/s eta 0:00:00
Requirement already satisfied: statsmodels>=0.13.2 in c:\users\caesar\anaconda3\lib\site-packages (from statsForecast) (0.13.2)
Collecting pyarrow>=0.15.1
  Downloading pyarrow-11.0.0-cp39-cp39-win_amd64.whl (20.6 MB)
     ---------------------------------------- 20.6/20.6 MB 1.8 MB/s eta 0:00:00
Collecting adagio>=0.2.4
  Downloading adagio-0.2.4-py3-none-any.whl (26 kB)
Collecting triad>=0.8.4
  Downloading triad-0.8.4-py3-none-any.whl (76 kB)
     ---------------------------------------- 76.8/76.8 kB 1.1 MB/s eta 0:00:00
Collecting fugue-sql-antlr>=0.1.6
  Downloading fugue-sql-antlr-0.1.6.tar.gz (154 kB)
     -------------------------------------- 154.6/154.6 kB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting qpd>=0.4.0
  Downloading qpd-0.4.0-py3-none-any.whl (187 kB)
     -------------------------------------- 187.8/187.8 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: jinja2 in c:\users\caesar\anaconda3\lib\site-packages (from fugue>=0.8.1->statsForecast) (2.11.3)
Collecting sqlglot
  Downloading sqlglot-11.4.5-py3-none-any.whl (242 kB)
     -------------------------------------- 242.9/242.9 kB 2.1 MB/s eta 0:00:00
Collecting numpy>=1.21.6
  Downloading numpy-1.21.6-cp39-cp39-win_amd64.whl (14.0 MB)
     ---------------------------------------- 14.0/14.0 MB 1.9 MB/s eta 0:00:00
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in c:\users\caesar\anaconda3\lib\site-packages (from numba>=0.55.0->statsForecast) (0.38.0)
Requirement already satisfied: setuptools in c:\users\caesar\anaconda3\lib\site-packages (from numba>=0.55.0->statsForecast) (63.4.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\caesar\anaconda3\lib\site-packages (from pandas>=1.3.5->statsForecast) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\caesar\anaconda3\lib\site-packages (from pandas>=1.3.5->statsForecast) (2.8.2)
Requirement already satisfied: patsy>=0.5.2 in c:\users\caesar\anaconda3\lib\site-packages (from statsmodels>=0.13.2->statsForecast) (0.5.2)
Requirement already satisfied: packaging>=21.3 in c:\users\caesar\anaconda3\lib\site-packages (from statsmodels>=0.13.2->statsForecast) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\caesar\anaconda3\lib\site-packages (from matplotlib->statsForecast) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\users\caesar\anaconda3\lib\site-packages (from matplotlib->statsForecast) (9.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\caesar\anaconda3\lib\site-packages (from matplotlib->statsForecast) (1.4.2)
Requirement already satisfied: cycler>=0.10 in c:\users\caesar\anaconda3\lib\site-packages (from matplotlib->statsForecast) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\caesar\anaconda3\lib\site-packages (from matplotlib->statsForecast) (4.25.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\caesar\anaconda3\lib\site-packages (from plotly->statsForecast) (8.0.1)
Collecting jupyter-dash>=0.4.2
  Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Collecting orjson<4.0.0,>=3.8.0
  Downloading orjson-3.8.9-cp39-none-win_amd64.whl (202 kB)
     -------------------------------------- 202.1/202.1 kB 1.4 MB/s eta 0:00:00
Collecting dash<3.0.0,>=2.2.0
  Downloading dash-2.9.2-py3-none-any.whl (10.2 MB)
     ---------------------------------------- 10.2/10.2 MB 1.9 MB/s eta 0:00:00
Collecting trace-updater>=0.0.8
  Downloading trace_updater-0.0.9-py3-none-any.whl (185 kB)
     -------------------------------------- 185.1/185.1 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: colorama in c:\users\caesar\anaconda3\lib\site-packages (from tqdm->statsForecast) (0.4.5)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Requirement already satisfied: Flask>=1.0.4 in c:\users\caesar\anaconda3\lib\site-packages (from dash<3.0.0,>=2.2.0->plotly-resampler->statsForecast) (1.1.2)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting antlr4-python3-runtime<4.12,>=4.11.1
  Downloading antlr4_python3_runtime-4.11.1-py3-none-any.whl (144 kB)
     -------------------------------------- 144.2/144.2 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: nest-asyncio in c:\users\caesar\anaconda3\lib\site-packages (from jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (1.5.5)
Requirement already satisfied: ipython in c:\users\caesar\anaconda3\lib\site-packages (from jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (7.31.1)
Collecting retrying
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Requirement already satisfied: requests in c:\users\caesar\anaconda3\lib\site-packages (from jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (2.18.4)
Requirement already satisfied: ipykernel in c:\users\caesar\anaconda3\lib\site-packages (from jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (6.15.2)
Collecting ansi2html
  Downloading ansi2html-1.8.0-py3-none-any.whl (16 kB)
Requirement already satisfied: six in c:\users\caesar\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels>=0.13.2->statsForecast) (1.16.0)
Collecting fs
  Downloading fs-2.4.16-py2.py3-none-any.whl (135 kB)
     -------------------------------------- 135.3/135.3 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\caesar\anaconda3\lib\site-packages (from jinja2->fugue>=0.8.1->statsForecast) (2.0.1)
Requirement already satisfied: itsdangerous>=0.24 in c:\users\caesar\anaconda3\lib\site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler->statsForecast) (2.0.1)
Requirement already satisfied: Werkzeug>=0.15 in c:\users\caesar\anaconda3\lib\site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler->statsForecast) (2.0.3)
Requirement already satisfied: click>=5.1 in c:\users\caesar\anaconda3\lib\site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler->statsForecast) (8.0.4)
Requirement already satisfied: appdirs~=1.4.3 in c:\users\caesar\anaconda3\lib\site-packages (from fs->triad>=0.8.4->fugue>=0.8.1->statsForecast) (1.4.4)
Requirement already satisfied: pyzmq>=17 in c:\users\caesar\anaconda3\lib\site-packages (from ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (23.2.0)
Requirement already satisfied: traitlets>=5.1.0 in c:\users\caesar\anaconda3\lib\site-packages (from ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (5.1.1)
Requirement already satisfied: tornado>=6.1 in c:\users\caesar\anaconda3\lib\site-packages (from ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (6.1)
Requirement already satisfied: debugpy>=1.0 in c:\users\caesar\anaconda3\lib\site-packages (from ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (1.5.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\caesar\anaconda3\lib\site-packages (from ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (0.1.6)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\caesar\anaconda3\lib\site-packages (from ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (7.3.4)
Requirement already satisfied: psutil in c:\users\caesar\anaconda3\lib\site-packages (from ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (5.9.0)
Requirement already satisfied: jedi>=0.16 in c:\users\caesar\anaconda3\lib\site-packages (from ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (0.18.1)
Requirement already satisfied: pickleshare in c:\users\caesar\anaconda3\lib\site-packages (from ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (0.7.5)
Requirement already satisfied: backcall in c:\users\caesar\anaconda3\lib\site-packages (from ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\caesar\anaconda3\lib\site-packages (from ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (3.0.20)
Requirement already satisfied: pygments in c:\users\caesar\anaconda3\lib\site-packages (from ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (2.11.2)
Requirement already satisfied: decorator in c:\users\caesar\anaconda3\lib\site-packages (from ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (5.1.1)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\caesar\anaconda3\lib\site-packages (from requests->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\caesar\anaconda3\lib\site-packages (from requests->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (2022.9.14)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\caesar\anaconda3\lib\site-packages (from requests->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\caesar\anaconda3\lib\site-packages (from requests->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (2.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\caesar\anaconda3\lib\site-packages (from jedi>=0.16->ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (0.8.3)
Requirement already satisfied: entrypoints in c:\users\caesar\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in c:\users\caesar\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (4.11.1)
Requirement already satisfied: wcwidth in c:\users\caesar\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (0.2.5)
Requirement already satisfied: pywin32>=1.0 in c:\users\caesar\anaconda3\lib\site-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel->jupyter-dash>=0.4.2->plotly-resampler->statsForecast) (302)
Building wheels for collected packages: plotly-resampler, fugue-sql-antlr
  Building wheel for plotly-resampler (pyproject.toml): started
  Building wheel for plotly-resampler (pyproject.toml): finished with status 'done'
  Created wheel for plotly-resampler: filename=plotly_resampler-0.8.3.2-cp39-cp39-win_amd64.whl size=56764 sha256=22aee69e4227ae542170a8569c2745c212188111aa6fae1f07644dd4d13ab237
  Stored in directory: c:\users\caesar\appdata\local\pip\cache\wheels\9e\36\06\4c11e300918011376af149098621ec7ebe06d8256566d43d51
  Building wheel for fugue-sql-antlr (setup.py): started
  Building wheel for fugue-sql-antlr (setup.py): finished with status 'done'
  Created wheel for fugue-sql-antlr: filename=fugue_sql_antlr-0.1.6-py3-none-any.whl size=158049 sha256=556f4ef3b7bdbedaf2537e09190e4a0f0d856e47b5d3f2ef70a99b5c08e8aa89
  Stored in directory: c:\users\caesar\appdata\local\pip\cache\wheels\57\b3\01\795c8a9ccaf9574fc3471b0199731c5526cf7c5e127db42a74
Successfully built plotly-resampler fugue-sql-antlr
Installing collected packages: trace-updater, sqlglot, dash-table, dash-html-components, dash-core-components, antlr4-python3-runtime, retrying, orjson, numpy, fs, ansi2html, pyarrow, triad, dash, jupyter-dash, fugue-sql-antlr, adagio, qpd, plotly-resampler, fugue, statsForecast
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
Successfully installed adagio-0.2.4 ansi2html-1.8.0 antlr4-python3-runtime-4.11.1 dash-2.9.2 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 fs-2.4.16 fugue-0.8.3 fugue-sql-antlr-0.1.6 jupyter-dash-0.4.2 numpy-1.21.6 orjson-3.8.9 plotly-resampler-0.8.3.2 pyarrow-11.0.0 qpd-0.4.0 retrying-1.3.4 sqlglot-11.4.5 statsForecast-1.5.0 trace-updater-0.0.9 triad-0.8.4

In [ ]:
model = StatsForecast(models=[AutoARIMA(season_length=7)], freq='D', n_jobs=-1)
model.fit(train)

In [16]:
df.index

RangeIndex(start=0, stop=48433, step=1)